MODEL:
  CONV:
    LAYERS: 12
    FILTERS: 32
  TRANSFORMER:
    NHEAD: 4
    NUM_LAYERS: 4
  LINEAR:
    DIM: 16
  CKPT: ''
    
TRAIN:
  OPTIMIZER:
    TYPE: 'AdamW'
    BASE_LR: 1.e-3
  SCHEDULER:
    MIN_LR: 1.e-4
  BATCH_SIZE: 256
  MAX_EPOCH: 5000

TEST:
  BATCH_SIZE: 512
