MODEL:
  CONV:
    LAYERS: 12
    FILTERS: 32
  TRANSFORMER:
    NHEAD: 4
    NUM_LAYERS: 4
  LINEAR:
    DIM: [32, 16]
    
TRAIN:
  OPTIMIZER:
    BASE_LR: 1.e-3
    MIN_LR: 1.e-5
  BATCH_SIZE: 128
  MAX_EPOCH: 5000

TEST:
  BATCH_SIZE: 512
