MODEL:
  CONV:
    LAYERS: 12
    FILTERS: 64
  LINEAR:
    DIM: [32, 16]

TRAIN:
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 1.e-4
  SCHEDULER:
    MIN_LR: 1.e-5
  BATCH_SIZE: 1024
  MAX_EPOCH: 5000

TEST:
  BATCH_SIZE: 2048
